{% set name = "pystencils" %}
{% set version = "0.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pystencils-{{ version }}.tar.gz
  sha256: c172849050bfae4598bc290ddf784fb47401aa6f44748b50534843f1fbf39312

build:
  number: 0
  skip: true  # [py>37]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
  run:
    - appdirs
    - joblib
    - numpy >=1.8.0
    - python
    - sympy >=1.2

test:
  imports:
    - pystencils
    - pystencils.backends
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://i10git.cs.fau.de/pycodegen/pystencils/
  license: AGPL-3.0-or-later
  license_family: GPL
  license_file: COPYING.txt
  summary: Run blazingly fast stencil codes on numpy arrays.
  description: |
    pystencils uses sympy to define stencil operations, that can be
    executed on numpy arrays. Exploiting the stencil structure makes 
    pystencils run faster than normal numpy code and even as Cython and
    numba, as demonstrated in this notebook.
  doc_url: https://i10git.cs.fau.de/pycodegen/pystencils/
  dev_url: https://i10git.cs.fau.de/pycodegen/pystencils/

extra:
  recipe-maintainers:
    - jan-janssen
