{% set name = "pystencils" %}
{% set version = "0.3.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pystencils-{{ version }}.tar.gz
  sha256: 360bfdfd4eb1bab01a615e1eb19b077aa90546a08fea8e67956dc17f9f7d5c39

build:
  number: 0
  skip: true  # [py2k]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
  run:
    - appdirs
    - joblib
    - numpy >=1.8.0
    - python
    - sympy >=1.2

test:
  imports:
    - pystencils
    - pystencils.backends
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://i10git.cs.fau.de/pycodegen/pystencils/
  license: AGPL-3.0-or-later
  license_family: GPL
  license_file: COPYING.txt
  summary: Run blazingly fast stencil codes on numpy arrays.
  description: |
    pystencils uses sympy to define stencil operations, that can be
    executed on numpy arrays. Exploiting the stencil structure makes 
    pystencils run faster than normal numpy code and even as Cython and
    numba, as demonstrated in this notebook.
  doc_url: https://i10git.cs.fau.de/pycodegen/pystencils/
  dev_url: https://i10git.cs.fau.de/pycodegen/pystencils/

extra:
  recipe-maintainers:
    - jan-janssen
