{% set name = "pystencils" %}
{% set version = "1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pystencils-{{ version }}.tar.gz
  sha256: c813e99e8c1632741987bb8068d5b485c374904f8fdd8f7074e37f1cd30604d8

build:
  number: 0
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
  run:
    - appdirs
    - joblib
    - numpy >=1.8.0
    - python
    - sympy <=1.10,>=1.6

test:
  imports:
    - pystencils
    - pystencils.backends
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://i10git.cs.fau.de/pycodegen/pystencils/
  license: AGPL-3.0-or-later
  license_family: GPL
  license_file: COPYING.txt
  summary: Run blazingly fast stencil codes on numpy arrays.
  description: |
    pystencils uses sympy to define stencil operations, that can be
    executed on numpy arrays. Exploiting the stencil structure makes 
    pystencils run faster than normal numpy code and even as Cython and
    numba, as demonstrated in this notebook.
  doc_url: https://i10git.cs.fau.de/pycodegen/pystencils/
  dev_url: https://i10git.cs.fau.de/pycodegen/pystencils/

extra:
  recipe-maintainers:
    - jan-janssen
